app:
  services:
    consultants:
      cache-refresh: off

integrations:
  cv-partner:
    apikey: dummy

mp:
  jwt:
    verify:
      issuer: dummy
      publickey: dummy

quarkus:
  log:
    category:
      "org.jboss.resteasy.reactive.client.logging":
        level: DEBUG
      "io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator":
        level: TRACE
        min-level: TRACE
  rest-client:
    cv-partner-api:
      url: dummy
    logging:
      body-limit: 20000
      scope: request-response
