app:
  services:
    consultants:
      cache-refresh: 10m

integrations:
  cv-partner:
    apikey: Token token=${CV_PARTNER_API_KEY}

mp:
  jwt:
    verify:
      issuer: ${KEY_ISSUER}
      publickey: ${KEY_PUBLIC}

quarkus:
  http:
    port: ${PORT:8080}
  openapi-generator:
    codegen:
      input-base-dir: src/main/resources/openapi/
  rest-client:
    cv-partner-api:
      url: ${CV_PARTNER_URL}
